-- =====================================================================
-- Fieldmark — DB-side scoring. Points are computed from the sightings table,
-- NOT the app. Run once in the Supabase SQL editor (idempotent, safe to re-run).
-- =====================================================================

-- 1) species -> rarity (matches species.json)
create table if not exists species_rarity (
  name   text primary key,
  rarity text not null
);
insert into species_rarity (name, rarity) values
  ('Mallard','common'),
  ('Barnacle Goose','common'),
  ('Great Spotted Woodpecker','common'),
  ('Eurasian Blackbird','common'),
  ('Hooded Crow','common'),
  ('Mew Gull','common'),
  ('White Wagtail','common'),
  ('Great Tit','common'),
  ('Fieldfare','common'),
  ('Whooper Swan','common'),
  ('Common Goldeneye','common'),
  ('Common Chaffinch','common'),
  ('House Sparrow','common'),
  ('Black-headed Gull','common'),
  ('Common Merganser','common'),
  ('Common Wood-Pigeon','common'),
  ('Eurasian Blue Tit','common'),
  ('Western Jackdaw','common'),
  ('Mute Swan','common'),
  ('Common Crane','common'),
  ('Eurasian Bullfinch','common'),
  ('Eurasian Oystercatcher','common'),
  ('European Pied Flycatcher','common'),
  ('Eurasian Magpie','common'),
  ('Canada Goose (canadensis Group)','common'),
  ('European Robin','common'),
  ('European Greenfinch','common'),
  ('Eurasian Wigeon','common'),
  ('Yellowhammer','common'),
  ('Barn Swallow','common'),
  ('Eurasian Tree Sparrow','common'),
  ('Eurasian Siskin','common'),
  ('Great Crested Grebe','common'),
  ('Gray/Purple Heron','common'),
  ('Northern Lapwing','common'),
  ('Herring Gull','common'),
  ('White-tailed Eagle','common'),
  ('Ring-necked Pheasant','common'),
  ('Common Tern','common'),
  ('Eurasian Jay','common'),
  ('Redwing','common'),
  ('Rock Pigeon','common'),
  ('Willow Tit','common'),
  ('Great Cormorant/European Shag','common'),
  ('Lesser Black-backed Gull','common'),
  ('Siberian Jay','common'),
  ('European Starling','common'),
  ('European Goldfinch','common'),
  ('Eurasian Treecreeper','common'),
  ('Brambling','common'),
  ('Northern Wheatear','common'),
  ('Eurasian Coot','common'),
  ('Black Woodpecker','common'),
  ('Bohemian Waxwing','common'),
  ('Song Thrush','common'),
  ('Common Redpoll','common'),
  ('Spotted Flycatcher','common'),
  ('Common Eider','common'),
  ('Arctic/Pacific Loon','common'),
  ('Green-winged Teal','common'),
  ('Reed Bunting','common'),
  ('Common Raven','common'),
  ('Graylag Goose','uncommon'),
  ('Wood Sandpiper','uncommon'),
  ('Common Sandpiper','uncommon'),
  ('Tufted Duck','uncommon'),
  ('Coal Tit','uncommon'),
  ('Western Capercaillie','uncommon'),
  ('Ruff','uncommon'),
  ('Willow Warbler','uncommon'),
  ('black grouse','uncommon'),
  ('Goldcrest','uncommon'),
  ('Hazel Grouse','uncommon'),
  ('Eurasian Sparrowhawk','uncommon'),
  ('Gray-headed Woodpecker','uncommon'),
  ('Eurasian Curlew','uncommon'),
  ('Crested Tit','uncommon'),
  ('Lesser Spotted Woodpecker','uncommon'),
  ('Pine Grosbeak','uncommon'),
  ('Common Redstart','uncommon'),
  ('Tree Pipit','uncommon'),
  ('Arctic Tern','uncommon'),
  ('White-throated Dipper','uncommon'),
  ('Osprey','uncommon'),
  ('Western Yellow Wagtail','uncommon'),
  ('White-backed Woodpecker','uncommon'),
  ('Eurasian Marsh-Harrier','uncommon'),
  ('Gadwall','uncommon'),
  ('Red-breasted Merganser','uncommon'),
  ('Eurasian Moorhen','uncommon'),
  ('Long-tailed Tit','uncommon'),
  ('Eurasian Kestrel','uncommon'),
  ('Greater White-fronted Goose','uncommon'),
  ('Common Swift','uncommon'),
  ('Eurasian Woodcock','uncommon'),
  ('Sedge Warbler','uncommon'),
  ('Greater Whitethroat','uncommon'),
  ('Common Chiffchaff','uncommon'),
  ('Eurasian Three-toed Woodpecker','uncommon'),
  ('Common Greenshank','uncommon'),
  ('Eurasian Linnet','uncommon'),
  ('Whinchat','uncommon'),
  ('Northern Shoveler','uncommon'),
  ('Lesser Whitethroat','uncommon'),
  ('Common Redshank','uncommon'),
  ('Horned Grebe','uncommon'),
  ('Red-necked Grebe','uncommon'),
  ('Gray-headed Chickadee','uncommon'),
  ('Common Snipe','uncommon'),
  ('Common Buzzard','uncommon'),
  ('Red-backed Shrike','uncommon'),
  ('Red Crossbill','uncommon'),
  ('Great Black-backed Gull','rare'),
  ('Eurasian Skylark','rare'),
  ('Great Egret','rare'),
  ('European Golden-Plover','rare'),
  ('Meadow Pipit','rare'),
  ('Northern Hawk Owl','rare'),
  ('Common Rosefinch','rare'),
  ('Dunnock','rare'),
  ('Great Gray Shrike','rare'),
  ('Eurasian Blackcap','rare'),
  ('Eurasian Pygmy-Owl','rare'),
  ('Common Ringed Plover','rare'),
  ('Eurasian Wren','rare'),
  ('Smew','rare'),
  ('Tawny Owl','rare'),
  ('Eurasian Hobby','rare'),
  ('Taiga/Tundra Bean-Goose','rare'),
  ('Eurasian Nutcracker','rare'),
  ('Willow Ptarmigan','rare'),
  ('Thrush Nightingale','rare'),
  ('Wood Warbler','rare'),
  ('Rustic Bunting','rare'),
  ('Great Gray Owl','rare'),
  ('Bluethroat','rare'),
  ('Green Sandpiper','rare'),
  ('Ural Owl','rare'),
  ('Common Pochard','rare'),
  ('Long-tailed Duck','rare'),
  ('Hawfinch','rare'),
  ('Common Cuckoo','rare'),
  ('Common House-Martin','rare'),
  ('Mistle Thrush','rare'),
  ('Little Gull','rare'),
  ('Snow Bunting','rare'),
  ('Northern Pintail','rare'),
  ('Spotted Redshank','rare'),
  ('Dunlin','rare'),
  ('Red-throated Loon','rare'),
  ('Parrot Crossbill','rare'),
  ('Caspian Tern','rare'),
  ('Red-flanked Bluetail','rare'),
  ('Stock Dove','epic'),
  ('European Honey-buzzard','epic'),
  ('Hen Harrier','epic'),
  ('Eurasian Nuthatch','epic'),
  ('Boreal Owl','epic'),
  ('Bank Swallow','epic'),
  ('Rough-legged Hawk','epic'),
  ('White-winged Scoter','epic'),
  ('Rook','epic'),
  ('Eurasian Eagle-Owl','epic'),
  ('Red-breasted Flycatcher','epic'),
  ('Tundra Bean-Goose','epic'),
  ('Blyth''s Reed Warbler','epic'),
  ('Garden Warbler','epic'),
  ('Icterine Warbler','epic'),
  ('Eurasian Wryneck','epic'),
  ('Little Bunting','epic'),
  ('Mandarin Duck','epic'),
  ('Eurasian Collared-Dove','epic'),
  ('Common Scoter','epic'),
  ('Long-eared Owl','epic'),
  ('Lapland Longspur','epic'),
  ('Water Rail','epic'),
  ('Temminck''s Stint','epic'),
  ('Short-eared Owl','epic'),
  ('Common Shelduck','epic'),
  ('Rock Ptarmigan','epic'),
  ('Garganey','epic'),
  ('Whimbrel','epic'),
  ('Golden Eagle','legendary'),
  ('Eurasian Nightjar','legendary'),
  ('Ortolan Bunting','legendary'),
  ('Great Bittern','legendary'),
  ('Bearded Reedling','legendary'),
  ('Merlin','legendary'),
  ('Black-tailed Godwit','legendary'),
  ('Bar-tailed Godwit','legendary'),
  ('Eurasian Dotterel','legendary'),
  ('Ruddy Turnstone','legendary'),
  ('Gray Wagtail','legendary'),
  ('Gray Partridge','legendary'),
  ('Brant','legendary'),
  ('Ring Ouzel','legendary'),
  ('Carrion Crow','legendary'),
  ('Red-necked Phalarope','legendary'),
  ('Long-tailed Jaeger','legendary'),
  ('White Stork','legendary'),
  ('Black Guillemot','legendary'),
  ('Pink-footed Goose','legendary'),
  ('Little Stint','legendary'),
  ('Black Redstart','legendary'),
  ('Parasitic Jaeger','legendary'),
  ('Citrine Wagtail','legendary'),
  ('Steller''s Eider','rare'),
  ('Pallid Harrier','rare'),
  ('Pied Avocet','rare'),
  ('Common Murre','uncommon'),
  ('Black Kite','epic'),
  ('Eurasian Hoopoe','epic'),
  ('Great Snipe','uncommon'),
  ('Pallas''s Leaf Warbler','uncommon'),
  ('Greenish Warbler','rare'),
  ('Glaucous Gull','epic'),
  ('Red Knot','rare'),
  ('Jack Snipe','uncommon'),
  ('Broad-billed Sandpiper','uncommon'),
  ('Northern Goshawk','epic'),
  ('Woodlark','rare'),
  ('European Serin','rare'),
  ('Two-barred Crossbill','rare'),
  ('Eurasian Golden Oriole','epic'),
  ('Common Kingfisher','rare'),
  ('Curlew Sandpiper','rare'),
  ('King Eider','rare'),
  ('Marsh Sandpiper','rare'),
  ('Greater Scaup','rare'),
  ('Red-throated Pipit','rare'),
  ('Spotted Crake','uncommon'),
  ('Eurasian Rock Pipit','rare'),
  ('European Bee-eater','epic'),
  ('Purple Sandpiper','epic'),
  ('Wood Duck','rare'),
  ('Black Swan','rare'),
  ('Black Tern','rare'),
  ('Peregrine Falcon','epic'),
  ('Montagu''s Harrier','epic'),
  ('Tundra Swan','rare'),
  ('Black-legged Kittiwake','rare'),
  ('Little Auk','uncommon'),
  ('Little Ringed Plover','rare'),
  ('Little Grebe','rare'),
  ('Red-footed Falcon','rare'),
  ('Red-breasted Goose','epic'),
  ('Terek Sandpiper','rare'),
  ('Corn Crake','epic'),
  ('Razorbill','uncommon'),
  ('Bar-headed Goose','epic'),
  ('Grey Plover','uncommon'),
  ('Arctic Redpoll','uncommon'),
  ('Gyrfalcon','rare'),
  ('Horned Lark','uncommon'),
  ('Snowy Owl','rare'),
  ('European Turtle Dove','rare'),
  ('Common Quail','rare'),
  ('Marsh Tit','uncommon'),
  ('Twite','uncommon'),
  ('Eurasian red squirrel','common'),
  ('Siberian Flying Squirrel','common'),
  ('European hare','common'),
  ('European roe deer','common'),
  ('hedgehog','common'),
  ('red fox','common'),
  ('moose','common'),
  ('reindeer','common'),
  ('white-tailed deer','common'),
  ('mountain hare','common'),
  ('European otter','uncommon'),
  ('brown bear','uncommon'),
  ('Eurasian lynx','uncommon'),
  ('European pine marten','rare'),
  ('Yellow-necked Mouse','rare'),
  ('raccoon dog','rare'),
  ('European rabbit','rare'),
  ('European badger','rare'),
  ('Asian Minute Shrew','rare'),
  ('Bank Vole','rare'),
  ('wolverine','rare'),
  ('grey seal','rare'),
  ('least weasel','epic'),
  ('European water vole','epic'),
  ('brown rat','epic'),
  ('stoat','epic'),
  ('European mole','epic'),
  ('Northern Bat','epic'),
  ('common shrew','legendary'),
  ('gray wolf','legendary'),
  ('ringed seal','legendary'),
  ('muskrat','legendary'),
  ('fallow deer','legendary'),
  ('American beaver','legendary'),
  ('field vole','legendary'),
  ('Harvest Mouse','legendary'),
  ('Eurasian Beaver','rare'),
  ('Grey Red-backed Vole','rare'),
  ('European Polecat','epic'),
  ('Laxmann''s Shrew','rare'),
  ('Common Vole','uncommon'),
  ('Northern Birch Mouse','rare'),
  ('House Mouse','rare'),
  ('Root Vole','rare'),
  ('Wood Lemming','rare'),
  ('American Mink','epic'),
  ('Taiga Shrew','rare'),
  ('Striped Field Mouse','rare'),
  ('Northern Red-backed Vole','epic'),
  ('Norway Lemming','rare'),
  ('Eurasian Water Shrew','epic'),
  ('Wild Boar','uncommon')
on conflict (name) do update set rarity = excluded.rarity;

alter table species_rarity enable row level security;
drop policy if exists "species_rarity_read" on species_rarity;
create policy "species_rarity_read" on species_rarity for select using (true);
grant select on species_rarity to anon, authenticated;

-- 2) scoring config — EDIT THESE NUMBERS to tune the game.
--    discover_pts = first time you ever record that species
--    repeat_pts   = each later sighting of a species you already have
create table if not exists rarity_points (
  rarity       text primary key,
  discover_pts int not null,
  repeat_pts   int not null
);
insert into rarity_points (rarity, discover_pts, repeat_pts) values
  ('common',     20,  5),
  ('uncommon',   35,  8),
  ('rare',       60, 12),
  ('epic',      100, 20),
  ('legendary', 200, 40)
on conflict (rarity) do update
  set discover_pts = excluded.discover_pts, repeat_pts = excluded.repeat_pts;

alter table rarity_points enable row level security;
drop policy if exists "rarity_points_read" on rarity_points;
create policy "rarity_points_read" on rarity_points for select using (true);
grant select on rarity_points to anon, authenticated;

-- 3) live per-player stats, computed from sightings (+ quest/co-op bonus_points).
--    Each sighting of a known species scores: discover_pts the first time,
--    repeat_pts every time after. Unknown junk (person/car) is ignored.
create or replace view player_stats
with (security_invoker = on) as
with occ as (   -- one row per (species occurrence) across all your sightings
  select s.owner, s.id, s.ts, lower(x.value) as sp
  from sightings s, lateral jsonb_array_elements_text(s.species) as x(value)
),
ranked as (
  select o.owner, o.sp, o.ts,
         row_number() over (partition by o.owner, o.sp order by o.ts asc, o.id) as rn
  from occ o
  join species_rarity sr on lower(sr.name) = o.sp   -- keep only known species
),
scored as (
  select r.owner, r.sp, r.rn,
         case when r.rn = 1 then rp.discover_pts else rp.repeat_pts end as pts
  from ranked r
  join species_rarity sr on lower(sr.name) = r.sp
  join rarity_points  rp on rp.rarity = sr.rarity
),
agg as (
  select owner,
         sum(pts)            as entry_points,
         count(distinct sp)  as species
  from scored
  group by owner
),
counts as (   -- number of actual sighting rows (photos), not species-occurrences
  select owner, count(*) as sightings from sightings group by owner
)
select
  l.owner,
  l.name,
  coalesce(c.sightings,0)                                 as sightings,
  coalesce(a.species,0)                                   as species,
  coalesce(a.entry_points,0) + coalesce(l.bonus_points,0) as points
from logbook l
left join agg    a on a.owner = l.owner
left join counts c on c.owner = l.owner;

grant select on player_stats to anon, authenticated;
